name: Publish for acceptance phase

on:
  push:
    branches: [ "acceptance" ]
  pull_request:
    branches: [ "acceptance" ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set headless property
        run: echo "JAVA_OPTS=-Djava.awt.headless=true" >> $GITHUB_ENV

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Build the application
        run: mvn package

      - name: Get current version
        id: get_version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      # Upload the build artifact for testing purposes
      # This is meant for people to download and test the application
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: application-${{ env.VERSION }}
          path: target/*.jar