name: Testing

on:
  push:
    branches: [ "tests" ]
  pull_request:
    branches: [ "tests" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
      security-events: write
      actions: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Run PMD
        id: pmd
        uses: pmd/pmd-github-action@v2
        with:
          version: '6.55.0'
          sourcePath: 'src/main/java'
          rulesets: 'rulesets/java/quickstart.xml,ruleset.xml'

#      - name: Upload SARIF file
#        uses: github/codeql-action/upload-sarif@v2
#        with:
#          sarif_file: pmd-report.sarif

      - name: Generate Jacoco report
        run: mvn jacoco:report

      - name: Upload Jacoco Report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/index.html